### PR TITLE
Symlinks for folder structure like https://github.com/joomla-extensions/weblinks

### PR DESCRIPTION
**Pull request by astridx**
Your repo is created for your extensions. I would understand you if you don't want to complicate it. Nevertheless, I ask you if you would like to make symlinks possible in an alternative way.

That's not nice yet. I've only done as far as it worked for me. I would never leave languages and plugins hard-coded.

Here is my proposal as a draft.

### CODE REVIEW

**Comment by laoneo** [comment]
Looks fine for me.

**Comment by laoneo** [comment]
Would be good if you can update the docs that the the folder structure for webserver can also be the one from the core.

**Comment by astridx** [comment]
Ready for review now ...

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
