### PR TITLE
Set environment variable

### PR DESCRIPTION
**Pull request by astridx**
Please see https://github.com/Digital-Peak/DPDocker/pull/19#discussion_r551149643

### CODE REVIEW

**Comment by laoneo** [comment]
Do we need it on CLI too?

**Comment by laoneo** [comment]
Why do you need these variables, just curious?

**Comment by astridx** [comment]
> Why do you need these variables, just curious?

Because Xdebug 3 has changed this configuration settings:
https://xdebug.org/docs/upgrade_guide#changed-xdebug.profiler_enable_trigger

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
